app/models/list.py
from app import db

class List(db.Model):

    __tablename__ = 'lists'

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(48))
    budget = db.Column(db.Float)
    user_lists = db.relationship('UserList', backref='list')
    user_id = db.Column(db.Integer, db.ForeignKey('users.id',  ondelete="CASCADE")) 

    @classmethod
    def select_all_lists(cls):
        lists = db.session.scalars(
                db.select(cls)
                )
        return lists

    @classmethod
    def select_the_list(cls, list_id):
        list = db.session.scalar(
                db.select(cls)
                .where(cls.id == list_id)
                )
        return list

    @classmethod
    def delete_the_list(cls, list):
        db.session.delete(list)
        db.session.commit()
        
    @classmethod
    def add_new_list(cls, name, budget, user_id):
        new_list = List(name=name, budget=budget, user_id=user_id)
        db.session.add(new_list)
        db.session.commit()
        return new_list

app/controllers/lists_controller.py
from app import db
from flask_sqlalchemy import SQLAlchemy
from flask import Blueprint, render_template, request, redirect, url_for
from flask_login import login_required
from app.models.list import List
from app.models.item import Item
from app.models.user_list import UserList
from app.models.store import Store
from app.models.user import User
from app.models.category import Category


lists_blueprint = Blueprint('lists', __name__)


@lists_blueprint.route('/lists')
def lists():
    lists = List.select_all_lists()    
    return render_template('/lists/lists.jinja', lists=lists) 


@lists_blueprint.route('/lists/<user_id>/<list_id>')
@login_required
def show_list(user_id, list_id): 
    items = Item.select_all_items()
    categories = Category.select_all_categories()
    list = List.select_the_list(list_id)
    on_list = UserList.group_items_on_the_list(list_id)
    user = User.select_user_by_id(user_id)
    total_value_of_items = UserList.calculate_value_of_all_items_on_the_list(list_id)
    return render_template('/lists/show_list.jinja', items=items, categories=categories, list=list, on_list=on_list, user=user, total_value_of_items=total_value_of_items)


@lists_blueprint.route('/lists/<list_id>/search', methods=['GET', 'POST'])
def search_item(list_id):
    item_name = request.form['item']
    list = List.select_the_list(list_id)
    user = User.match_user_with_list(list_id) 
    item = Item.select_search_item(item_name)
    on_list = UserList.group_items_on_the_list(list_id)
    items = Item.select_all_items()
    total_value_of_items = UserList.calculate_value_of_all_items_on_the_list(list_id)
    return render_template('/lists/search_item.jinja', list=list, item=item, on_list=on_list, items=items, user=user, total_value_of_items=total_value_of_items)


@lists_blueprint.route('/lists/<id>/add', methods=['POST'])
def add_item(id):
    item_name = request.form['item_name']
    item = Item.select_search_item(item_name)
    items = Item.select_all_items()
    list = List.select_the_list(id)
    UserList.add_new_item_to_the_list(list.id, item.id)
    on_list = UserList.group_items_on_the_list(list.id)
    user = User.match_user_with_list(list.id)
#     stores = Store.select_user_stores(user.id)
    total_value_of_items = UserList.calculate_value_of_all_items_on_the_list(list.id)
    return render_template('/lists/search_item.jinja', list=list, item=item, on_list=on_list, items=items, user=user, total_value_of_items=total_value_of_items)

    # removed stores=stores from return statement

@lists_blueprint.route('/lists/<list_id>/<user_id>/delete', methods=['POST'])
def delete_item(list_id, user_id):
    item_name = request.form['item_name']
    print(item_name)
    item = Item.select_search_item(item_name)
    UserList.delete_item_on_the_list(list_id, item.id)    
    return redirect(url_for('lists.show_list', user_id=user_id, list_id=list_id))

app/controllers/users_controllers.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, flash
from app import db
from flask_login import current_user, login_user, logout_user, login_required
from app.models.user import User
from app.models.item import Item
from app.models.user_layouts import UserLayouts
from app.models.category import Category
from app.models.list import List 
from app.models.store import Store
from app.forms.forms import CreateList, CreateItem
from app.forms.login import LoginForm
from app.forms.registration import RegistrationForm
from werkzeug.urls import url_parse

users_blueprint = Blueprint('users', __name__)


@users_blueprint.route('/', methods=['GET', 'POST'])
def home():
    if current_user.is_authenticated:
        return redirect(url_for('users.user', name=current_user.username))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first() 
        if user is None or not user.check_password(form.password.data):
            return redirect(url_for('users.home'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('users.home')
        return redirect(url_for('users.user', name=user.username))
    return render_template('index.jinja', form=form)


@users_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.home'))

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data) 
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.home'))
    return render_template('/users/register.jinja', title='Register', form=form)


@users_blueprint.route('/add/user', methods=['GET', 'POST'])
def add_user():
    if request.method == 'POST':
        full_name = request.form['username']
        new_user = User(username=full_name)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('users.home'))
    return render_template('/users/add_user.jinja')


@users_blueprint.route('/delete/<user_id>', methods=['POST'])
def delete_user(user_id):
    user = User.select_user_by_id(user_id)
    User.delete_user_by_id(user)
    return redirect(url_for('users.home'))
   


@users_blueprint.route('/user/<name>', methods=['GET', 'POST'])
@login_required
def user(name):
    # user = User.select_user_by_name(name)
    lists = List.select_all_lists()
    form = CreateList()
    return render_template('/users/user.jinja', lists=lists, form=form)


@users_blueprint.route('/user/<user_id>/add_list', methods=['POST', 'GET'])
def add_list(user_id):
    user = User.select_user_by_id(user_id)
    # name = request.form['name']
    # budget = request.form['budget']
    form = CreateList()
    if form.validate_on_submit():
        new_list = List.add_new_list(form.name.data, form.budget.data, user_id)
        return redirect(url_for('lists.show_list', user_id=user_id, list_id=new_list.id))
    return redirect(url_for('users.user', name=user.username))




@users_blueprint.route('/delete/<user_id>/list/<list_id>', methods=['POST'])
def delete_list(user_id, list_id):
    list = List.select_the_list(list_id)
    List.delete_the_list(list)
    user = User.select_user_by_id(user_id)
    return redirect(url_for('users.user', name=user.username))
    


@users_blueprint.route('/user/<user_id>/create_layout', methods=['GET', 'POST'])
def create_layout(user_id):
    user = User.select_user_by_id(user_id)
    categories = Category.select_all_categories()
    if request.method == 'POST':
        layout = request.form['store']
        address= request.form['address']
        Store.add_new_store(layout, address, user_id)
    stores = Store.select_user_stores(user_id)
    return render_template('/users/create_layout.jinja', categories=categories, user=user, stores=stores)


@users_blueprint.route('/user/<user_id>/create_layout/sort', methods=['GET', 'POST'])
def create_sort_method(user_id):
    store_name = request.form['store']
    category_name = request.form['category']
    store = Store.select_store_by_name(store_name)
    category = Category.select_category_by_name(category_name)
    UserLayouts.create_new_layout(store.id, category.id)
    user = User.select_user_by_id(user_id)
    categories = Category.select_all_categories()
    return render_template('/users/create_sort_method.jinja', store=store, user=user, categories=categories)

@users_blueprint.route('/add_item', methods=['GET', 'POST'])
def add_new_item_to_database():
    categories = Category.select_all_categories()
    form = CreateItem(obj=categories) 
    form.item_category.choices = [(c.id, c.name) for c in Category.query.order_by('name')]
    if form.validate_on_submit():
        if Item.select_search_item(form.name.data) == None:
            new_item = Item(name=form.name.data, category=form.item_category.data, price=form.price.data)
            db.session.add(new_item)
            db.session.commit()
        else:
            flash("You already have this product :)")
    return render_template('/items/add_item.jinja', categories=categories, form=form)

app/templates/lists/lists.jinja
{% extends 'base.jinja' %}

{% block content %}


    {% for list in lists %}
        <p><a href="{{ url_for('lists.show_list', id=list.id) }}">{{ list.name }}</a></p>
        
    {% endfor %}
    
{% endblock content %}

app/templates/lists/search_item.jinja
{% extends 'base.jinja' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='search_item.css') }}">
<section class="search__page">
    {# <p>This will be sortation method</p> #}
    {# <select name="sort" id="sort">
        {% for store in stores %}
            <option value="{{ store.name }}">{{ store.name }}</option>
        {% endfor %}
    </select> #}
    <div class="search__page__entries">
        <h1 class="search__page__list__name">{{ list.name }}</h1>
        <h3 class="search__page__list__name__subtitle">Items on your list</h3>
        <div class="search__page__entries__section">
            {% for key, value in on_list.items() %}
            {# <p class="entries__section__entry">{{ key }} {{ value }}</p> #}
            <form action="{{ url_for('lists.delete_item', list_id=list.id, user_id=user.id) }}" class="entries__section__form" method="post">
                <div class="list__page__entry__wrapper"> 
                    <button class="delete__button__from__list" type="submit" value="{{ key }}" name="item_name">{{ key }}</button>
                    <div class="list__page__entry__line"></div>
                    <p class="list__page__entry__count">{{ value }}</p>
                </div>
            </form>
            {% endfor %}
        </div>
    </div>
    <div class="combained__total__value__and__item">
        <div class="search__page__searched__item">
            <form action="{{ url_for('lists.add_item', id=list.id) }}" method="POST">
            <button class="create__button" name="item_name" type="submit" value="{{ item.name}}">Add
            </button>
            </form>
            <h4 class="searched__item__text">{{ item.name }} £{{ item.price }}</h4>
        </div>
        <div class="search__page__total__value">
            <h4 class="search__page__total__value__text">Your list costing you:</h4>
            <p class="search__page__total__value__amount">£{{ total_value_of_items }}</p>
        </div>
    </div>
    <div class="search__page__add__entries">
        <div class="search__page__search__add">
            <form action="{{ url_for('lists.search_item', list_id=list.id) }}" method="POST">
                <button class="create__button search__page__button">Search</button>
                <label for="item"></label>
                <input class="user__input"type="text" name="item" id="item">
            </form>
        </div>
        </form>
        <p class="list__page__add__entries__text">Click on item to add to the list</p>
        <section class="list__age__add__entries__form">
        {% for item in items  %}
            <form action="{{ url_for('lists.add_item', id=list.id) }}" method="POST">
                <button class="add__entries__form__item" name="item_name" type="submit" value="{{ item.name}}">{{ item.name }} {{ item.price }}</button>
            </form>
        {% endfor %}
        </section>
    </div>
</section>
{% endblock content %}

app/templates/lists/show_list.jinja
{% extends 'base.jinja' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='show_list.css') }}">
    
<section class="list__page">
    <div class="list__page__entries">
        <h1 class="list__page__list__name">{{ list.name }} </h1>
        <h3 class="list__page__list__name__subtitle">Items on your list</h3>
        <div class="list__page__entries__section">
            {% for key, value in on_list.items() %}
            <form action="{{ url_for('lists.delete_item', list_id=list.id, user_id=user.id) }}" class="entries__section__form" method="post">
                <div class="list__page__entry__wrapper"> 
                    <button class="delete__button__from__list" type="submit" value="{{ key }}" name="item_name">{{ key }}</button>
                    <div class="list__page__entry__line"></div>
                    <p class="list__page__entry__count">{{ value }}</p>
                </div>
            </form>
            {% endfor %}
        </div> 
        <form action="{{ url_for('users.delete_list', user_id=user.id, list_id=list.id) }}" method="POST">
            <div class="list__page__delete__button__wrapper">
                <button class="delete__button" type="submit">Delete</button>
                <p>{{ list.name }}</p>
            </div>
        </form>
    </div>
    <div class="list__page__total__value">
        <h4 class="list__page__total__value__text">Your list costing you:</h4>
        <p class="list__page__total__value__amount">£{{ total_value_of_items }}</p>
    </div>

    {# <p>cateogries here</p>
    {% for category in categories %}
        <p>{{ category }}</p>
    
    {% endfor %}
    {% for row in categories %}
        <p>{{ row.name }}</p>
    
    {% endfor %} #}
    
    
    <div class="list__page__add__entries">
        <form action="{{ url_for('lists.search_item', list_id=list.id) }}" method="POST">
            <button class="create__button list__page__button">Search</button>
            <label for="item"></label>
            <input class="user__input"type="text" name="item" id="item">
        </form>
        
        <p class="list__page__add__entries__text">Click on item to add to the list</p>
        <section class="list__age__add__entries__form">
        {% for item in items  %}
            <form action="{{ url_for('lists.add_item', id=list.id) }}" method="POST">
                <button class="add__entries__form__item" name="item_name" type="submit" value="{{ item.name}}">{{ item.name }} {{ item.price }}</button>
            </form>
        {% endfor %}
        </section>
        <p><a href="{{ url_for('users.create_layout', user_id=user.id) }}">Check this new mega function that you'll love</a></p>
    </div>
</section>
{% endblock content %}