app/models/user.py
from app import db, login
from app.models.list import List
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin

class User(UserMixin, db.Model):

    __tablename__ = 'users'

    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(30))
    email = db.Column(db.String(64)) 
    password_hash = db.Column(db.String(128))
    lists = db.relationship('List', backref='user', cascade="all, delete-orphan")
    stores = db.relationship('Store', backref='user')

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return '<User {}>'.format(self.username)
        
        

    @classmethod
    def select_all_users(cls):
        users = db.session.scalars(
                db.select(cls)
                )
        return users

    @classmethod
    def select_user_by_id(cls, user_id):
        user = db.session.scalar(
                    db.select(cls)
                    .where(cls.id == user_id)
                    )
        return user

    @classmethod
    def match_user_with_list(cls, list_id):
        user = db.session.scalar(
                db.select(cls)
                .join(List, cls.id == List.user_id)
                )
        return user
# fix that for stores variable in add_item > lists blueprint

    @classmethod
    def select_user_by_name(cls, name):
        user = db.session.scalar(
                db.select(cls)
                .where(cls.username == name)
                )
        return user

    @classmethod
    def delete_user_by_id(cls, user):
        db.session.delete(user)
        db.session.commit()

@login.user_loader
def load_user(id):
    return User.query.get(int(id))

app/controllers/users_controllers.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, flash
from app import db
from flask_login import current_user, login_user, logout_user, login_required
from app.models.user import User
from app.models.item import Item
from app.models.user_layouts import UserLayouts
from app.models.category import Category
from app.models.list import List 
from app.models.store import Store
from app.forms.forms import CreateList, CreateItem
from app.forms.login import LoginForm
from app.forms.registration import RegistrationForm
from werkzeug.urls import url_parse

users_blueprint = Blueprint('users', __name__)


@users_blueprint.route('/', methods=['GET', 'POST'])
def home():
    if current_user.is_authenticated:
        return redirect(url_for('users.user', name=current_user.username))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first() 
        if user is None or not user.check_password(form.password.data):
            return redirect(url_for('users.home'))
        login_user(user, remember=form.remember_me.data)
        next_page = request.args.get('next')
        if not next_page or url_parse(next_page).netloc != '':
            next_page = url_for('users.home')
        return redirect(url_for('users.user', name=user.username))
    return render_template('index.jinja', form=form)


@users_blueprint.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('users.home'))

@users_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    form = RegistrationForm()
    if form.validate_on_submit():
        user = User(username=form.username.data, email=form.email.data) 
        user.set_password(form.password.data)
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('users.home'))
    return render_template('/users/register.jinja', title='Register', form=form)


@users_blueprint.route('/add/user', methods=['GET', 'POST'])
def add_user():
    if request.method == 'POST':
        full_name = request.form['username']
        new_user = User(username=full_name)
        db.session.add(new_user)
        db.session.commit()
        return redirect(url_for('users.home'))
    return render_template('/users/add_user.jinja')


@users_blueprint.route('/delete/<user_id>', methods=['POST'])
def delete_user(user_id):
    user = User.select_user_by_id(user_id)
    User.delete_user_by_id(user)
    return redirect(url_for('users.home'))
   


@users_blueprint.route('/user/<name>', methods=['GET', 'POST'])
@login_required
def user(name):
    # user = User.select_user_by_name(name)
    lists = List.select_all_lists()
    form = CreateList()
    return render_template('/users/user.jinja', lists=lists, form=form)


@users_blueprint.route('/user/<user_id>/add_list', methods=['POST', 'GET'])
def add_list(user_id):
    user = User.select_user_by_id(user_id)
    # name = request.form['name']
    # budget = request.form['budget']
    form = CreateList()
    if form.validate_on_submit():
        new_list = List.add_new_list(form.name.data, form.budget.data, user_id)
        return redirect(url_for('lists.show_list', user_id=user_id, list_id=new_list.id))
    return redirect(url_for('users.user', name=user.username))




@users_blueprint.route('/delete/<user_id>/list/<list_id>', methods=['POST'])
def delete_list(user_id, list_id):
    list = List.select_the_list(list_id)
    List.delete_the_list(list)
    user = User.select_user_by_id(user_id)
    return redirect(url_for('users.user', name=user.username))
    


@users_blueprint.route('/user/<user_id>/create_layout', methods=['GET', 'POST'])
def create_layout(user_id):
    user = User.select_user_by_id(user_id)
    categories = Category.select_all_categories()
    if request.method == 'POST':
        layout = request.form['store']
        address= request.form['address']
        Store.add_new_store(layout, address, user_id)
    stores = Store.select_user_stores(user_id)
    return render_template('/users/create_layout.jinja', categories=categories, user=user, stores=stores)


@users_blueprint.route('/user/<user_id>/create_layout/sort', methods=['GET', 'POST'])
def create_sort_method(user_id):
    store_name = request.form['store']
    category_name = request.form['category']
    store = Store.select_store_by_name(store_name)
    category = Category.select_category_by_name(category_name)
    UserLayouts.create_new_layout(store.id, category.id)
    user = User.select_user_by_id(user_id)
    categories = Category.select_all_categories()
    return render_template('/users/create_sort_method.jinja', store=store, user=user, categories=categories)

@users_blueprint.route('/add_item', methods=['GET', 'POST'])
def add_new_item_to_database():
    categories = Category.select_all_categories()
    form = CreateItem(obj=categories) 
    form.item_category.choices = [(c.id, c.name) for c in Category.query.order_by('name')]
    if form.validate_on_submit():
        if Item.select_search_item(form.name.data) == None:
            new_item = Item(name=form.name.data, category=form.item_category.data, price=form.price.data)
            db.session.add(new_item)
            db.session.commit()
        else:
            flash("You already have this product :)")
    return render_template('/items/add_item.jinja', categories=categories, form=form)

app/templates/users/add_user.jinja
{% extends 'base.jinja' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='add_user.css') }}">
   <div class="user__section">
       <h1 class="user__section__title">Add new user here</h1>
       <form class="user__section__form" action="{{ url_for('users.add_user') }}" method="POST">
            <label class="user__section__form__username" for="fullname">Username</label>
            <input class="user__input user__input--color" type="text" name="fullname" id="fullname">
            <button type="submit" class="create__button">Confirm</button>
       </form>
   </div>
{% endblock content %}

app/templates/users/create_layout.jinja
{% extends 'base.jinja' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='create_layout.css') }}">
<div class="create__layout">
    <div class="create__layout__new">
        <h2>Create new layout</h2>
        
        <form class="create__layout__form" action="{{ url_for('users.create_layout', user_id=user.id) }}" method="POST">
            <label for="store">Name of the layout</label>
            <input type="text" name="store" id="store">
            <label for="address">Address</label>
            <input type="text" name="address" id="address">
            <button type="submit">Create layout</button>
        </form>
    </div>
    
    <div class="create__sortation">
        {% if stores == 'empty' %}
            <p>You don't have any layouts</p>
        {% endif %}
        <form action="{{ url_for('users.create_sort_method', user_id=user.id) }}" method="post">
            <select name="store" id="store">
            {% for store in stores %}
                <option value="{{ store.name }}">{{ store.name }}</option>
            <input type="hidden" name="category" value="fruit">
            {% endfor %}
            <button type="submit">Select the store</button>
            </select>
        </form>
        <form action="{{ url_for('users.create_layout', user_id=user.id )}}" method="post">
        {% for category in categories %}
            <button class="product" name="category" value="{{ category.name }}" type="submit">{{ category.name }}</button>
        {% endfor %}
        </form>
    </div>
</div>

{% endblock content %}

app/templates/users/create_sort_method.jinja
{% extends 'base.jinja' %}

{% block content %}
   <p>this is method sortation website</p> 
   <p>{{ store.name }}</p>
   <p>{{ user.fullname }}</p>
   <form action="{{ url_for('users.create_sort_method', user_id=user.id) }}" method="post">
    {% for category in categories %}
        <button class="product" name="category" value="{{ category.name }}" type="submit">{{ category.name }}</button>
        <input type="hidden" name="store" value="{{ store.name }}">
    {% endfor %}
   </form>
{% endblock content %}

app/templates/users/register.jinja
{% extends 'base.jinja' %}

{% block content %}
<h1>Register</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.username.label }}<br>
        {{ form.username(size=32) }}<br>
        {% for error in form.username.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.email.label }}<br>
        {{ form.email(size=64) }}<br>
        {% for error in form.email.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password.label }}<br>
        {{ form.password(size=32) }}<br>
        {% for error in form.password.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>
        {{ form.password2.label }}<br>
        {{ form.password2(size=32) }}<br>
        {% for error in form.password2.errors %}
        <span style="color: red;">[{{ error }}]</span>
        {% endfor %}
    </p>
    <p>{{ form.submit }}</p>
</form>
    
{% endblock content %}
    

app/templates/users/user.jinja
{% extends 'base.jinja' %}

{% block content %}
<link rel="stylesheet" href="{{ url_for('static', filename='user.css') }}">

<section class="user__page__section">
    <div class="user__page__section__left">
        <div class="user__page_welcome__message__wrapper">
            <h1 class="user__page__welcome__message">It's good to see you</h1>
            <h1 class="user__page__welcome__message user__page__welcom__message__user__name">{{ current_user.username }}</h1>
            <h3 class="user__page__welcome__message__subtitle">Your lists are here</h3>
        </div>
        
        <div class="user__page__section__left__list__wrapper">
        {% for list in current_user.lists %}
            <div class="user__page__section__left__list">
                <h1 class="user__page__section__list__item"><a href="{{ url_for('lists.show_list', list_id=list.id, user_id=current_user.id) }}">{{ list.name }}</a></h1>
                {# <form action="{{ url_for('users.delete_list', user_id=user.id, list_id=list.id) }}" method="POST">
                <button class="delete__button" type="submit">Delete<button>
                </form> #}
            </div>
        {% endfor %}
        </div>
    </div>
    
    <div class="user__page__section__right">
        <h4 class="user__page__section__right__text">Create a new list</h4>
        {# <form class="user__page__section__right__form" action="{{ url_for('users.add_list', user_id=user.id) }}" method="POST">
            <div class="user__page__section__right__input">
                <label for="name">Name</label>
                <input class="user__input" type="text" required name="name" id="name">
            </div>
            <div class="user__page__section__right__input">
                <label for="budget">Budget</label>
                <input class="user__input" required type="number" name="budget" id="budget">
            </div>
            <button class="create__button" type="submit">Create</button>
        </form> #}
        <form action="{{ url_for('users.add_list', user_id=current_user.id) }}" method="post">
            {{ form.hidden_tag() }}
            <p>
                {{ form.name.label }}<br>
                {{ form.name(size=32) }}<br>
                {% for error in form.name.errors %}
                    <li>{{ error }}</li> 
                {% endfor %} 
            </p><br>
            <p>
                {{ form.budget.label }}<br>
                {{ form.budget }}
            </p>
            <br>
            <p class="create__button">{{ form.submit() }}</p>
        </form>
        <div class="user__page__section__right__delete_user">
            <p class="delete__user__form__text">Delete your account</p>
            <form class="delete__user__form" action="{{ url_for('users.delete_user', user_id=current_user.id) }}" method="post">
                <button class="delete__button" type="submit">Delete</button>
            </form>
        </div>
    </div>
</section>

{% endblock content %}
 